trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-18.04

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'artifactory-x100'
    sourceRepo: 'npm'
    
- script: |
    ls -la
    ls -la ./.jfrog

