#kubectl apply -f deploy/sm.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sm
  labels:
    app: sm
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: sm
        tier: web
    spec:
      containers:
        - name: jetti
          image: eu.gcr.io/jetti-x100/jetti-api:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_PORT
              value: "1433"
            - name: DB_HOST
              value: JETTI-DB-01
            - name: DB_NAME
              value: sm
            - name: DB_USER
              value: jetti
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-db-credentials
                  key: password
            - name: DB_TASK_USER
              value: jetti_task
            - name: DB_TASK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-db-credentials
                  key: password
            - name: REDIS_DB_HOST
              value: redis-master
            - name: JTW_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key
                  key: JTW_KEY
            - name: EXCHANGE_ACCESS_KEY
              value: "ei362NQNrfyLMrzJ0fECu1gQn7Hbv1Y5KllJIQGbbgY="
            - name: REFRESH_ID
              value: "00022"
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: sm
  labels:
    app: sm
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: sm
  ports:
  - port: 8080
    targetPort: 8080